config/routes.rb
Rails.application.routes.draw do
  get 'search_patron/search'
  get 'search_patron/results'
  get 'search_res/search'
  get 'search_res/results'
  get 'search_res/checkout'
  get '/search' => 'search_res#search', :as => 'search_page'
  get 'welcome/index'
  root 'welcome#index'
  resources :books do
    resources :reviews
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :author, presence: true
	validates :isbn, presence: true, length: { is: 10 }, numericality: { only_integer: true }, uniqueness: true
	validates :copies, presence: true, numericality: { only_integer: true }
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def new
		@book = Book.new
	end
	def show
		@search_type_t = params[:search_type_t]
		@search_type_a = params[:search_type_a]
		@search_type_i = params[:search_type_i]
		@search = params[:search]
		@book = Book.find(params[:id])
	end
	def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to books_path
		else
			render 'new'
		end
	end
	def index
		@books = Book.all
	end
	def edit
		@search_type_t = params[:search_type_t]
		@search_type_a = params[:search_type_a]
		@search_type_i = params[:search_type_i]
		@search = params[:search]
		@id = params[:id]
		@book = Book.find(params[:id])
	end
	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			#redirect_to @book
			#render plain: params[:book][:search].inspect
			#redirect_to(book_path(:search => params[:book][:search], :search_type_t => params[:book][:search_type_t], :search_type_a => params[:book][:search_type_a], :search_type_i => params[:book][:search_type_i]))
			redirect_to(search_res_search_path)
			
		else
			render 'edit' 
		end
	end
	def destroy
		@book = Book.find(params[:id]) 
		@book.destroy
		redirect_to books_path 
	end
	
	private
	def book_params
		params.require(:book).permit(:title, :author, :isbn, :copies)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@search_type_t = params[:search_type_t]
		@search_type_a = params[:search_type_a]
		@search_type_i = params[:search_type_i]
		@search = params[:search]
		@review = Review.new
	end
	def create
		@book = Book.find(params[:book_id])
		@review = @book.reviews.create(params.require(:review).permit(:reviewer, :body))
		redirect_to book_reviews_path(@book, :search => params[:review][:search], :search_type_t => params[:review][:search_type_t], :search_type_a => params[:review][:search_type_a], :search_type_i => params[:review][:search_type_i])
	end
	def index
		@search_type_t = params[:search_type_t]
		@search_type_a = params[:search_type_a]
		@search_type_i = params[:search_type_i]
		@search = params[:search]
		@book = Book.find(params[:book_id])
		@reviews = @book.reviews
	end
end

app/controllers/search_patron_controller.rb
class SearchPatronController < ApplicationController
  def search
  end

  def results
    @books = Book.all
    @results = []
    @search_type_t = params[:search_type_t]
    @search_type_a = params[:search_type_a]
    @search_type_i = params[:search_type_i]
    @search = params[:search]
    if params[:search_type_t] == '0' and params[:search_type_a] == '0' and params[:search_type_i] == '0'
      @results = @books
    end
    if params[:search_type_t] == '1'
      @books.each do |book|
        if book.title.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
    if params[:search_type_a] == '1'
      @books.each do |book|
        if book.author.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
    if params[:search_type_i] == '1'
      @books.each do |book|
        if book.isbn.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
  end
end

app/controllers/search_res_controller.rb
class SearchResController < ApplicationController
  def search
  end
  
  def checkout
    @book = Book.find(params[:id])
    @book.copies = @book.copies - 1
    @book.save
    @search_type_t = params[:search_type_t]
    @search_type_a = params[:search_type_a]
    @search_type_i = params[:search_type_i]
    @search = params[:search]
    redirect_to search_res_search_path(:search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search)
  end
  
  def results
    @books = Book.all
    @results = []
    @search_type_t = params[:search_type_t]
    @search_type_a = params[:search_type_a]
    @search_type_i = params[:search_type_i]
    @search = params[:search]
    if params[:search_type_t] == '0' and params[:search_type_a] == '0' and params[:search_type_i] == '0'
      params[:search_type_t] = '1'
      params[:search_type_a] = '0'
      params[:search_type_i] = '0'
    end
    if params[:search_type_t] == '1'
      @books.each do |book|
        if book.title.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
    if params[:search_type_a] == '1'
      @books.each do |book|
        if book.author.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
    if params[:search_type_i] == '1'
      @books.each do |book|
        if book.isbn.match(/#{@search}/i)
          @results.append(book)
        end
      end
    end
    end
    # if @search_type == 'Title'
    #   @books.each do |book|
    #     if book.title.match(/#{@search}/i)
    #       @results.append(book)
    #     end
    #   end
    # if @search_type == 'Author'
    #   @books.each do |book|
    #     if book.author.match(/#{@search}/i)
    #       @results.append(book)
    #     end
    #   end
    # if @search_type == 'ISBN'
    #   @books.each do |book|
    #     if book.isbn.match(/#{@search}/i)
    #       @results.append(book)
    #     end
    #   end
    # end
  #end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_patron_helper.rb
module SearchPatronHelper
end

app/helpers/search_res_helper.rb
module SearchResHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= form_with scope: :book, url: books_path, local: true do |form| %>
<% if @book.errors.any? %>
<div id="error_explanation"> <h2>
	error(s) prohibited this book from being saved: </h2>
	<ul>
	<% @book.errors.full_messages.each do |msg| %> <li><%= msg %></li>
	<% end %> 
	</ul>
	</div>
<% end %>
<% end %>
<%= form_with model: @book, local: true do |form| %>
	<p>
	<%= form.label :title %><br>
	<%= form.text_field :title %> 
	</p>
	<p>
	<%= form.label :author %><br>
	<%= form.text_field :author %>
	</p>
	<p>
		<%= form.label :isbn %><br>
		<%= form.text_field :isbn %>
	</p>
	<p>
		<%= form.label :copies %><br>
		<%= form.text_field :copies %>
		</p>
	<p>
		<p style="display:none;">
			<%= form.label :search %><br>
			<%= form.text_field :search, value: @search %>
			</p>
		<p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_title %><br>
			<%= form.text_field :search_type_t, value: @search_type_t %>
		</p>
	<p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_author %><br>
			<%= form.text_field :search_type_a, value: @search_type_a %>
		</p>
	<p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_isbn %><br>
			<%= form.text_field :search_type_i, value: @search_type_i %>
		</p>
	<p>
	
	<%= form.submit %>
	</p>
<% end %>
<%= link_to 'Back', search_res_results_path(:search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search) %>

app/views/books/index.html.erb
<h1>Listing All Books</h1>
<table> 
<tr>
<th>Title</th> 
<th>Author</th> 
<th>ISBN</th> 
<th>Copies</th>
<th></th>
<!-- <th></th> -->
<th></th> 
</tr>
<% @books.each do |book| %> 
<tr>
<td><%= book.title %></td> 
<td><%= book.author %></td> 
<td><%= book.isbn %></td> 
<td><%= book.copies %></td> 
<td><%= link_to 'Show',
book_path(book) %></td> 
<td><%= link_to 'Edit', edit_book_path(book) %>
</td>
<!-- <td><%= link_to 'Destroy', book_path(book),
	method: :delete,
	data: { confirm: 'Are you sure?' } %>
</td> -->
</tr>
<% end %> 
</table>
<p><%= link_to 'New book', new_book_path %></p>
<p><%= link_to 'Back to Search', search_res_search_path %></p>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with scope: :book, url: books_path, local: true do |form| %>
<% if @book.errors.any? %>
<div id="error_explanation"> <h2>
	error(s) prohibited this book from being saved: </h2>
	<ul>
	<% @book.errors.full_messages.each do |msg| %> <li><%= msg %></li>
	<% end %> 
	</ul>
	</div>
<% end %>
<% end %>

<%= form_with scope: :book, url: books_path, local: true do |form| %> <p>
	<%= form.label :title %><br>
	<%= form.text_field :title %> </p>
	<p>
	<%= form.label :author %><br>
	<%= form.text_field :author %>
	</p>
	<p>
		<%= form.label :isbn %><br>
		<%= form.text_field :isbn %>
	</p>
	<p>
		<%= form.label :copies %><br>
		<%= form.text_field :copies %>
		</p>
	<p>
	<%= form.submit %>
	</p>
	<% end %>
	<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
	<strong>Title: </strong>
	<%= @book.title %>
</p>
<p>
	<strong>Author: </strong>
	<%= @book.author %>
</p>
<p>
	<strong>ISBN: </strong>
	<%= @book.isbn %>
</p>
<p>
	<strong>Copies: </strong>
	<%= @book.copies %>
</p>
<%= link_to 'Back', search_res_results_path(:search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search) 
%>
<%= #link_to 'Back', books_path 
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h3>Book Reviews for <%= Book.find(params[:book_id]).title %> </h3> 
<p>by <%= Book.find(params[:book_id]).author %> (<%= Book.find(params[:book_id]).isbn %>) </p>
<table> 
<tr>
<th>Name</th> 
<th>Reviews</th> 
</tr>
<% @reviews.each do |review| %> 
<tr>
<td><%= review.reviewer %></td> 
<td><%= review.body %></td> 
</tr>
<% end %> 
</table>
<p><%= link_to 'Back to Results', search_patron_results_path(:search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search) %></p>

app/views/reviews/new.html.erb
<h1>New Review for <%= Book.find(params[:book_id]).title %></h1>

<%= form_with scope: :review, url: book_reviews_path, local: true do |form| %> <p>
	<%= form.label :reviewer %><br>
	<%= form.text_field :reviewer %> </p>
	<p>
	<%= form.label :body %><br>
	<%= form.text_field :body %>
	</p>
	<p style="display:none;">
		<%= form.label :search %><br>
		<%= form.text_field :search, value: @search %>
	</p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_title %><br>
			<%= form.text_field :search_type_t, value: @search_type_t %>
		</p>
	<p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_author %><br>
			<%= form.text_field :search_type_a, value: @search_type_a %>
		</p>
	<p>
	<p>
		<p style="display:none;">
			<%= form.label :search_type_isbn %><br>
			<%= form.text_field :search_type_i, value: @search_type_i %>
		</p>
	<p>
	<%= form.submit %>
	</p>
	<% end %>
<p><%= link_to 'Back to Results', search_patron_results_path(:search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search) %></p>

app/views/search_patron/results.html.erb
<h1>Results</h1>
<p><%= #render plain: params.inspect 
%></p>
<table> 
	<tr>
	<th>Title</th> 
	<th>Author</th> 
	<th>ISBN</th> 
	<!-- <th>Copies</th> -->
	<th>Review Book</th>
	<th></th>
	</tr>
	<% @results.each do |book| %> 
	<tr>
	<td><%= book.title %></td> 
	<td><%= book.author %></td> 
	<td><%= book.isbn %></td> 
	<!-- <td><%= book.copies %></td> -->
	<td><%= link_to 'Add Review', new_book_review_path(book, :search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search)  %>
	</td>
	<td><%= link_to 'See Reviews', book_reviews_path(book, :search_type_t => @search_type_t, :search_type_i => @search_type_i, :search_type_a => @search_type_a, :search => @search) %>
	</td>
	</tr>
	<% end %> 
	</table>
	<p><%= link_to 'Back to Search', search_patron_search_path %></p>

app/views/search_patron/search.html.erb
<h1>Search</h1>
<%= form_with url: search_patron_results_path, local: true, method: :get do |form| %> 
	<p>
	<%= form.label :search %><br>
	<%= form.text_field :search %> for
	<%= form.check_box :search_type_t %> 
	<%= form.label :search_type_title, 'Title' %>
	<%= form.check_box :search_type_a %> 
	<%= form.label :search_type_author, 'Author' %>
	<%= form.check_box :search_type_i %> 
	<%= form.label :search_type_isbn, 'ISBN' %>
	</p>
	<p>
	<%= form.submit 'search'%>
	</p>
<% end %>
<p><%= link_to 'Home', root_path %></p>

app/views/search_res/checkout.html.erb
<p><%= render plain: params[:id].inspect %></p>

app/views/search_res/results.html.erb
<h1>Results</h1>
<p><%= #render plain: params.inspect 
%></p>
<table> 
	<tr>
	<th>Title</th> 
	<th>Author</th> 
	<th>ISBN</th> 
	<!-- <th>Copies</th> -->
	<th></th>
	<th></th>
	</tr>
	<% @results.each do |book| %> 
	<tr>
	<td><%= book.title %></td> 
	<td><%= book.author %></td> 
	<td><%= book.isbn %></td> 
	<!-- <td><%= book.copies %></td> -->
	<td><%= link_to 'Edit', "../books/#{book.id}/edit?search=#{@search}&search_type_t=#{@search_type_t}&search_type_a=#{@search_type_a}&search_type_i=#{@search_type_i}&id=#{book.id}" %>
	</td>
	<% if book.copies > 0 %>
	<td><%= link_to 'Check Out', "./checkout/?search=#{@search}&search_type_t=#{@search_type_t}&search_type_a=#{@search_type_a}&search_type_i=#{@search_type_i}&id=#{book.id}" %>
	</td>
	<% end %> 
	</tr>
	<% end %> 
	</table>
	<p><%= link_to 'Back to Search', search_res_search_path %></p>
	<p><%= #render plain: params.inspect 
	%></p>

app/views/search_res/search.html.erb
<h1>Search</h1>
<%= link_to 'All Books', books_path %>
<p><%= link_to 'New book', new_book_path %></p>
<%= form_with url: search_res_results_path, local: true, method: :get do |form| %> 
	<p>
	<%= form.label :search %><br>
	<%= form.text_field :search %> for
	<%= #form.select :search_type, ['Title', 'Author', 'ISBN'] 
	%>
	<%= form.check_box :search_type_t %> 
	<%= form.label :search_type_title, 'Title' %>
	<%= form.check_box :search_type_a %> 
	<%= form.label :search_type_author, 'Author' %>
	<%= form.check_box :search_type_i %> 
	<%= form.label :search_type_isbn, 'ISBN' %>
	</p>
	<p>
	<%= form.submit 'search'%>
	</p>
<% end %>
<p><%= link_to 'Home', root_path %></p>

app/views/welcome/index.html.erb
<h1>Library</h1>
<%= link_to 'Adminstrator', search_res_search_path %>
<p><%= link_to 'Patron', search_patron_search_path %></p>